/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "FANTASY",
  "description": "",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "./assets/img/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "./assets/img/bug.gif",
        "heroText": null,
        "tagline": "本人学识渊博、经验丰富，代码风骚、效率恐怖，c/c++、java、php无不精通，熟练掌握各种框架，深山苦练20余年，一天只睡4小时，千里之外定位问题，瞬息之间修复上线。身体强壮、健步如飞，可连续编程100小时不休息，讨论技术方案5小时不喝水，上至带项目、出方案，下至盗账号、威胁pm，啥都能干。泡面矿泉水已备好，学校不支持编程已辍学，家人不支持编程已断绝关系，老婆不支持编程已离婚，小孩不支持编程已送孤儿院，备用电源万兆光纤永不断电断网，门口已埋雷无人打扰",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "关于网站",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "关于内容",
            "details": "内容有在B站上白嫖的，也有在实际开发中遇到的，目的是为了后面能快速查阅相关知识以及定位Bug或者解决方案（至少会往这一方向靠，如果头发还没秃完的话）"
          },
          {
            "title": "关于本人",
            "details": "某不知名气人选手，退役熬夜选手，拖延俱乐部顶级VIP，国家一级抬杠运动员，夜宵外卖一品鉴赏师，修图照骗大赛常驻嘉宾，资深话题终结者，贫困大赛形象代言人。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present Fantasy"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-f68c2ab0",
      "path": "/",
      "lastUpdated": "11/24/2020, 1:09:57 AM"
    },
    {
      "title": "javascript",
      "frontmatter": {},
      "regularPath": "/front-end/javascript.html",
      "relativePath": "front-end/javascript.md",
      "key": "v-d1b877f0",
      "path": "/front-end/javascript.html",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ],
      "lastUpdated": "11/24/2020, 10:56:15 PM"
    },
    {
      "title": "javascript",
      "frontmatter": {},
      "regularPath": "/javascript.html",
      "relativePath": "javascript.md",
      "key": "v-0a9c71c5",
      "path": "/javascript.html",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ],
      "lastUpdated": "11/24/2020, 10:56:15 PM"
    },
    {
      "title": "以及标签",
      "frontmatter": {},
      "regularPath": "/java.html",
      "relativePath": "java.md",
      "key": "v-32aa925b",
      "path": "/java.html",
      "headers": [
        {
          "level": 2,
          "title": "fantasy",
          "slug": "fantasy"
        }
      ],
      "lastUpdated": "11/24/2020, 1:09:57 AM"
    },
    {
      "title": "sql",
      "frontmatter": {},
      "regularPath": "/sql.html",
      "relativePath": "sql.md",
      "key": "v-114421b3",
      "path": "/sql.html",
      "lastUpdated": "11/24/2020, 10:56:15 PM"
    }
  ],
  "themeConfig": {
    "logo": "./assets/img/logo.png",
    "nav": [
      {
        "text": "前端",
        "items": [
          {
            "text": "JavaScript",
            "link": "/front-end/javascript"
          },
          {
            "text": "Vue",
            "link": "/front-end/vue"
          },
          {
            "text": "Angular",
            "link": "/front-end/angular"
          }
        ]
      },
      {
        "text": "JAVA",
        "link": "/java"
      },
      {
        "text": "数据库",
        "link": "/sql"
      },
      {
        "text": "计算机基础",
        "link": "/computer-basic"
      }
    ],
    "sidebar": "auto",
    "lastUpdated": "Last Updated"
  }
}